### ISSUE TITLE
Output log file not showing and nothing gets uploaded

### ISSUE THREAD

**Issue by DiameterEffect** [7x11x13/songs-to-youtube#49]
Hello again lol, Im having issue with getting this app to upload a song to youtube but it creates the MKV file  and then it just stalls for a really long time. Using songs-to-youtube on my other computer works and i see the logs but using it on my laptop doesnt work

![image](https://github.com/7x11x13/songs-to-youtube/assets/65675954/3e441202-c567-46f4-8d1c-11695d615f61)

What could be the issue, do i need to clear the cache or something or no?

**Comment by DiameterEffect** [comment]
![image](https://github.com/7x11x13/songs-to-youtube/assets/65675954/dcccbcde-76ad-41c3-9c80-2fceeb6f4a39)
as you can see the app is using a lot of memory and cpu power but nothing isn't working, i reinstalled the app and still nothing

**Comment by authenyoo** [comment]
it has to do with your ffmpeg version
i deleted my ffmpeg, downloaded a ffmpeg 4.4 binary from https://ffbinaries.com/downloads, put it on /usr/local/bin then it worked

**Comment by DiameterEffect** [comment]
> it has to do with your ffmpeg version i deleted my ffmpeg, downloaded a ffmpeg 4.4 binary from https://ffbinaries.com/downloads, put it on /usr/local/bin then it worked

It doesnt work, or i couldnt get it to work because i cant find /usr/local/bin

**Comment by Nevorist** [comment]
I had the same problem and it was fixed by uninstalling the latest version of FFmpeg through scoop. 

To give context to the problem, the software got this issue after i installed scoop to install geckodriver and chromedriver. My best guess is that scoop installed the latest version of FFmpeg without me noticing.
Thankfully you can just input "scoop uninstall ffmpeg" in Powershell and it should work as long as you already have an older version installed (5.1.2 works fine for me). No need to install it in /usr/local/bin.

Hope it helps. I don't know anything about programming though so i could be entirely wrong.

**Comment by DiameterEffect** [comment]
> I had the same problem and it was fixed by uninstalling the latest version of FFmpeg through scoop.
> 
> To give context to the problem, the software got this issue after i installed scoop to install geckodriver and chromedriver. My best guess is that scoop installed the latest version of FFmpeg without me noticing. Thankfully you can just input "scoop uninstall ffmpeg" in Powershell and it should work as long as you already have an older version installed (5.1.2 works fine for me). No need to install it in /usr/local/bin.
> 
> Hope it helps. I don't know anything about programming though so i could be entirely wrong.

Thank you! this worked
